name: Makefile CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - name: Setup Go
       uses: actions/setup-go@v3
       with:
          go-version: "1.19.0"
          
     - uses: actions/checkout@v2
      
     - name: Install dependencies
       run: make

     - name: Test
       run: make unit_test
